### ISSUE TITLE
Question: Substitute PD6/ADC9 for another pin?

### ISSUE THREAD

**Issue by mbaran5** [floppes/ClassicMiniControllerAdapter#1]
I was looking to see if I could wire this up to an Arduino Pro Micro that I already own and put inside of an existing (but terrible) Wii Classic to USB case, but noticed one of the pins used is PD6/ADC9 which is unused on a Pro Micro. Could another pin be substituted that isn't already in use? 

Using this as my reference for which pins are mapped to which from the ATMEGA32U4: http://cdn.sparkfun.com/datasheets/Dev/Arduino/Boards/Pro_Micro_v13b.pdf

Thanks!

**Comment by floppes** [comment]
Yes, that's no problem. I²C is done in software so any digital pin works. In `controller_adapter.ino` just modify the line `#define PIN_SCL2		12` to your preferred pin.

**Comment by mbaran5** [comment]
Cool, thank you! I realized after posting this that both of my Pro Micros are 5v/16mhz, so I will need to rethink the plan.
